/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author user
 */
public class ManagePersonDetails extends javax.swing.JPanel {

    JPanel viewProfilePanel;
    PersonDirectory personDirectory;
    /**
     * Creates new form ManagePersonDetails
     */
    public ManagePersonDetails(JPanel container, PersonDirectory directory) {
        initComponents();
        viewProfilePanel = container;
        personDirectory = directory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnViewDetails1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearchBox = new javax.swing.JTextField();

        setBackground(new java.awt.Color(223, 225, 238));

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Home City", "Home zip Code", "Work City", "Work Zip Code"
            }
        ));
        jScrollPane1.setViewportView(tblPerson);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("List Of People");

        btnSearch.setBackground(new java.awt.Color(59, 89, 152));
        btnSearch.setText("Search for person");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewDetails1.setBackground(new java.awt.Color(59, 89, 152));
        btnViewDetails1.setText("View Details");
        btnViewDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetails1ActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(59, 89, 152));
        btnDelete.setText("Delete Profile ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearchBox.setText("Type Name or Street Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewDetails1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnSearch, btnViewDetails1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDetails1)
                    .addComponent(btnDelete))
                .addGap(0, 132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(!txtSearchBox.getText().isBlank()){
            String searchText = txtSearchBox.getText();
            Person foundPerson = personDirectory.searchPerson(searchText);

            System.out.println("btnSearchActionPerformed");
            System.out.println(searchText);
            System.out.println(foundPerson);
            if(foundPerson != null){
                CreatePersonProfile panel = new CreatePersonProfile(viewProfilePanel, personDirectory, foundPerson, true);
                viewProfilePanel.add("VewAccountJPanel", panel);
                CardLayout layout = (CardLayout) viewProfilePanel.getLayout();
                layout.next(viewProfilePanel);
            }else{
                JOptionPane.showConfirmDialog(null, "Profile not found. Please check the name or address and try again", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Please type first in the search bar", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }                                         
   
    private void btnViewDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetails1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPerson.getSelectedRow();

        if(selectedRow >= 0){
            Person selectedPerson = (Person) tblPerson.getValueAt(selectedRow, 0);

            CreatePersonProfile panel = new CreatePersonProfile(viewProfilePanel, personDirectory, selectedPerson, true);
            viewProfilePanel.add("VewAccountJPanel", panel);
            CardLayout layout = (CardLayout) viewProfilePanel.getLayout();
            layout.next(viewProfilePanel);
        }else{
            JOptionPane.showConfirmDialog(null, "Please select a row from the list", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewDetails1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPerson;
    private javax.swing.JTextField txtSearchBox;
    // End of variables declaration//GEN-END:variables

     public void populateTable() {
       DefaultTableModel model =  (DefaultTableModel) tblPerson.getModel();
       model.setRowCount(0);
       
       for(Person p : personDirectory.getPersonList()){
            Object[] row = new Object[6];
            row[0] = p;
            row[1] = p.getLastName();
            
            Address homeAddr = p.getHomeAddress();
            row[2] = homeAddr.getCity();
            row[3] = homeAddr.getZipCode();
            
            Address workAddr = p.getWorkAddress();
            System.out.println(workAddr.getCity());
            row[4] = workAddr.getCity();
            
            System.out.println(workAddr.getZipCode());
            row[5] = workAddr.getZipCode();
            model.addRow(row);
        }
       
    }
}
